### ISSUE TITLE
Using fb-flo with polymer

### ISSUE THREAD

**Issue by sepans** [facebook/fb-flo#103]
I am trying to use fb-flo with Polymer. The file reloads in the browser but it doesn't have any effect and in dev-tools it looks as if the file has local modifications AND the warning icon.

![screen shot 2015-10-19 at 6 57 34 pm](https://cloud.githubusercontent.com/assets/687513/10593624/4c747ac4-7693-11e5-9f58-9cd64ec36792.png)

I know there might be many other complexities in using polymer with fb-flo but what does this mean?

**Comment by amasad** [comment]
That's strange. I'm not familiar enough with polymer to be able to help. You can leave this open maybe someone else may run into this and provide input.
