### ISSUE TITLE
js is not hotswapped

### ISSUE THREAD

**Issue by tabraiz12** [facebook/fb-flo#24]
Js not getting updated

flo logs
[session] requested resource update /assets/v2/explore.js

terminal logs
[Flo] File changed javascripts/v2/explore.js
[Server] Broadcasting { match: 'indexOf',
  contents: <Buffer 2f 2f 3d 20 72 65 71 75 69 72 65 20 22 63 6d 33 2f 63 6f 64 65 6d 69 72 72 6f 72 22 0a 2f 2f 3d 20 72 65 71 75 69 72 65 20 22 63 6d 33 2f 6d 6f 64 65 2f ...>,
  resourceURL: 'assets/v2/explore.js' }

var flo = require('fb-flo'),
    path = require('path'),
    fs = require('fs');

var server = flo(
  'app/assets',
  {
    port: 8888,
    host: '127.0.0.1',
    verbose: true,
    glob: [
       // All JS files in `sourceDirToWatch` and subdirectories
      '**/*.js',
       // All CSS files in `sourceDirToWatch` and subdirectories
      '**/*.css'
    ]
  },
  function resolver(filepath, callback) {
    // 1. Call into your compiler / bundler.
    // 2. Assuming that `bundle.js` is your output file, update `bundle.js`
    //    and `bundle.css` when a JS or CSS file changes.
    callback({
      resourceURL:  'assets/v2/'+path.basename(filepath),
      contents: fs.readFileSync('app/assets/'+filepath),
    });
  }
);

**Comment by amasad** [comment]
reopen if this still an issue
