### ISSUE TITLE
updating a file in the devtools-sourcespanel that is in a devtools-workspace and mapped.

### ISSUE THREAD

**Issue by te7ris** [facebook/fb-flo#29]
Hi,
its not really a bug, because the file is still updated (obvsly because I changed it in the devtools) but the flo-extension is logging the following error

[session] flo failed to update, this shouldn't happen please report it: {"code":"E_NOTSUPPORTED","description":"Object does not support requested operation: %s","details":["Resource is not editable"],"isError":true}
---
EDIT
well It actually is a bug. Because when I change the file in an external Editor it failes to update (same error appears in the flo-log)...
---
Maxi
p.s. WHY on earth is the text so big?

**Comment by amasad** [comment]
Reopen if this is still an issue.
