### ISSUE TITLE
make it easier to use

### ISSUE THREAD

**Issue by jonathanong** [facebook/fb-flo#41]
ex. a lot of the stuff in the readme is verbose and should be "defaults".

ideally i want to be able to do something like `fb-flo build/` and just watch for changes in the build directory. my build process will be the one creating all the stuff in build, and you could assume everything in `build/` is being served. 

main point though is setting up a server should be easier, at least in the readme :)

**Comment by amasad** [comment]
Not very actionable task, but will be a priority next time I look at this.
