### ISSUE TITLE
Please mention the `fb-flo-reload` event in the documentation

### ISSUE THREAD

**Issue by MihaiValentin** [facebook/fb-flo#53]
While taking a look through the source code of flo-client, I found that an event called `fb-flo-reload` gets dispatched on `window`.

I plan to use this to do custom logic in my app after any resource gets changed. My only question is why isn't this described in the documentation? Do you intend to keep it? The only I found regarding this event was in this ticket: #26

If that's something to be kept, I can make a pull request with a documentation update on this useful feature.

Thoughts?

**Comment by amasad** [comment]
this was merged
