### ISSUE TITLE
fb-flo status blocked on "connecting"

### ISSUE THREAD

**Issue by Guibz** [facebook/fb-flo#79]
Hello,

I've install a webserver with vagrant and puphpet. I've checked if the file changed are detected and it works when node.js is launched. But when I tried connecting fb-flo to my server it just blocks in the chrome panel on 'connecting' status:

[connection] Reconnecting in 500
[connection] Connecting to ws://local.dev:8888/
[connection] Failed to connect with 1006

Any clues? Thanx in advance.

**Comment by amasad** [comment]
Might be a problem with port forwarding?
