### ISSUE TITLE
Determine if chrome debugger is stopped before actually refreshing code

### ISSUE THREAD

**Issue by unphased** [facebook/fb-flo#82]
I am using fb-flo to work on my web project and it is very very awesome, especially for live CSS editing. However the problem that I have always had is that whenever I absentmindedly leave the chrome debugger stopped on something, and then go and change the JS code (which in turn causes fb-flo to hotswap the new JS) it throws Chrome into a completely borked state where mousemove events stop working entirely for the remainder of the lifetime of the browser tab process, including if I F5-refresh the entire page. 

Therefore I would very much like to know if it is possible to determine from the fb-flo client `update` callback whether or not the Chrome Debugger is stopped on something and hopefully if it is I can also go ahead and unpause script execution, somehow. But if it turns out I can't programmatically unpause the debugger, maybe there is still a way that I can at least cancel the live code update so that my entire tab does not become trashed.

**Comment by amasad** [comment]
Unfortunately currently there is no way to hook into the debugger from the extension. So there is no way to unpause or even just know that it's active. Any other suggestions?

**Comment by unphased** [comment]
That's as i suspected. I suppose it may be impossible for various reasons depending on how the process and VM sandbox system is architected...

**Comment by amasad** [comment]
I remember seeing somewhere that it's planned to provide access. It would open a bit more possibilities then. I'll close the issue because it's not actionable but we can keep discussing
