### ISSUE TITLE
Features questions

### ISSUE THREAD

**Issue by dancancro** [facebook/fb-flo#98]
Hi

I maintain a central [knowledgebase](http://www.dancancro.com/compare-app-technologies/) of web technology features and recently added this to it. Could someone clarify what the following features listed on the project home page mean?

Live edit images
Remote file system
Editor choice

Thanks,
Dan

**Comment by amasad** [comment]
>Live edit images

You can update images and see the result in real time

>Remote file system

Your code doesn't have to live on your local machine

>Editor choice

You can use your favorite editor for live editing

**Comment by dancancro** [comment]
Ah, sorry. I thought this was a thing to let you use your browser to edit source files. Got it now!
